services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_NUM_THREAD=4
      - OLLAMA_MAX_LOADED_MODELS=1
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3

  agno-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - vscode-server:/home/vscode/.vscode-server
    ports:
      - "8888:8888"
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - PYTHONPATH=/workspace/src
    depends_on:
      ollama:
        condition: service_healthy
    command: sleep infinity
    user: vscode

volumes:
  ollama_data:
  vscode-server:
